version: '3.9'
services:
  front:
    build:
      context: .
    ports:
    - '3000:3000'
    volumes:
    - .:/onebitflix-front
    command: bash start.sh
    stdin_open: true
    networks:
      - onebitflix-net

networks:
  onebitflix-net:
    name: onebitflix-net
    external: true