version: '3.9'
services:
  front:
    build:
      context: .
    ports:
    - '3001:3001'
    volumes:
    - .:/onebitflix-front
    command: bash start.sh
    stdin_open: true
    environment:
      - NEXT_PUBLIC_BASEURL=http://api:3000
      - STATIC_FILES_BASEURL=http://localhost:3000
    networks:
      - onebitflix-net

networks:
  onebitflix-net:
    name: onebitflix-net
    external: true